version: '3'
services:
  auth-service:
    volumes:
      - ./auth-service:/usr/src/app
  user-service:
    volumes:
      - ./user-service:/usr/src/app
  product-service:
    volumes:
      - ./product-service:/app  # Mounts the code into the container for live reloading
    environment:
      NODE_ENV: development  # Sets the environment to development
