version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-service
      - product-service
    networks:
      - backend

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      auth-service:
        condition: service_healthy

  product-service:
    build: ./product-service
    ports:
      - "3003:3003"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      user-service:
        condition: service_healthy

networks:
  backend:
    driver: bridge
