# version: '3.4' # Use version 3.4 or higher to ensure healthcheck support

# services:
#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       auth-service:
#         condition: service_healthy
#       user-service:
#         condition: service_healthy
#       product-service:
#         condition: service_healthy
#     networks:
#       - backend

#   auth-service:
#     build: ./auth-service
#     networks:
#       - backend
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   user-service:
#     build: ./user-service
#     networks:
#       - backend
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

#   product-service:
#     build: ./product-service
#     networks:
#       - backend
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# networks:
#   backend:
#     driver: bridge

##########################################

version: '3.4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./path/to/entrypoint.sh:/docker-entrypoint.d/custom-entrypoint.sh
    networks:
      - backend
    depends_on:
      - auth-service
      - user-service
      - product-service
    command: ["/docker-entrypoint.d/custom-entrypoint.sh"]
  auth-service:
    build: ./auth-service
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-service:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  user-service:
    build: ./user-service
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://user-service:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  product-service:
    build: ./product-service
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://product-service:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    driver: bridge

