version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
  user-service:
    build: ./user-service
    ports:
      - "3002:3002"
  product-service:
    build: ./product-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3003:3003"
